// widgets/GiftCategory.dart
import '../models/gift_item.dart';

const List<GiftCategory> categories = [
    GiftCategory(
      id: 'classic',
      label: 'Cadeaux',
      emoji: '🎁',
      gifts: [
        GiftItem(emoji: "🌹", name: "Rose", cost: 2),
        GiftItem(emoji: "🔥", name: "Flamme", cost: 5),
        GiftItem(emoji: "💎", name: "Diamant", cost: 15),
        GiftItem(emoji: "🍀", name: "Trèfle", cost: 3),
        GiftItem(emoji: "🍎", name: "Pomme", cost: 4),
        GiftItem(emoji: "🍌", name: "Banane", cost: 2),
        GiftItem(emoji: "🍇", name: "Raisin", cost: 3),
        GiftItem(emoji: "🍓", name: "Fraise", cost: 5),
        GiftItem(emoji: "🍉", name: "Pastèque", cost: 6),
        GiftItem(emoji: "🍒", name: "Cerise", cost: 4),
        GiftItem(emoji: "🍍", name: "Ananas", cost: 7),
        GiftItem(emoji: "🥥", name: "Noix de coco", cost: 8),
        GiftItem(emoji: "🥝", name: "Kiwi", cost: 5),
        GiftItem(emoji: "🥭", name: "Mangue", cost: 6),
        GiftItem(emoji: "🍋", name: "Citron", cost: 3),
        GiftItem(emoji: "🍊", name: "Orange", cost: 4),
        GiftItem(emoji: "🍐", name: "Poire", cost: 3),
        GiftItem(emoji: "🍏", name: "Pomme verte", cost: 4),
        GiftItem(emoji: "🥑", name: "Avocat", cost: 5),
        GiftItem(emoji: "🥦", name: "Brocoli", cost: 2),
        GiftItem(emoji: "🥬", name: "Laitue", cost: 2),
        GiftItem(emoji: "🥒", name: "Concombre", cost: 3),
        GiftItem(emoji: "🌽", name: "Maïs", cost: 3),
        GiftItem(emoji: "🥕", name: "Carotte", cost: 2),
        GiftItem(emoji: "🧄", name: "Ail", cost: 1),
        GiftItem(emoji: "🧅", name: "Oignon", cost: 1),
        GiftItem(emoji: "🥔", name: "Pomme de terre", cost: 2),
        GiftItem(emoji: "🍠", name: "Patate douce", cost: 3),
        GiftItem(emoji: "🥐", name: "Croissant", cost: 4),
        GiftItem(emoji: "🥯", name: "Bagel", cost: 4),
        GiftItem(emoji: "🍞", name: "Pain", cost: 2),
        GiftItem(emoji: "🥖", name: "Baguette", cost: 3),
        GiftItem(emoji: "🧇", name: "Gaufre", cost: 5),
        GiftItem(emoji: "🧈", name: "Beurre", cost: 1),
        GiftItem(emoji: "🥚", name: "Œuf", cost: 1),
        GiftItem(emoji: "🧀", name: "Fromage", cost: 2),
        GiftItem(emoji: "🍗", name: "Poulet", cost: 6),
        GiftItem(emoji: "🥩", name: "Steak", cost: 7),
        GiftItem(emoji: "🥓", name: "Bacon", cost: 5),
        GiftItem(emoji: "🍖", name: "Côtelette", cost: 6),
        GiftItem(emoji: "🍤", name: "Crevette", cost: 8),
        GiftItem(emoji: "🍣", name: "Sushi", cost: 10),
        GiftItem(emoji: "🍱", name: "Bento", cost: 12),
        GiftItem(emoji: "🍛", name: "Curry", cost: 9),
        GiftItem(emoji: "🍜", name: "Nouilles", cost: 7),
        GiftItem(emoji: "🍲", name: "Soupe", cost: 6),
        GiftItem(emoji: "🍥", name: "Naruto", cost: 4),
        GiftItem(emoji: "🥟", name: "Dumpling", cost: 5),
        GiftItem(emoji: "🦀", name: "Crabe", cost: 9),
        GiftItem(emoji: "🦞", name: "Homard", cost: 12),
        GiftItem(emoji: "🦐", name: "Crevette géante", cost: 10),
      ],
    ),
    GiftCategory(
      id: 'interactive',
      label: 'Interactifs',
      emoji: '⚡',
      gifts: [
        GiftItem(emoji: "👏", name: "Applaudir", cost: 3),
        GiftItem(emoji: "🎉", name: "Confetti", cost: 8),
        GiftItem(emoji: "💥", name: "Explosion", cost: 12),
        GiftItem(emoji: "✨", name: "Étoiles", cost: 5),
        GiftItem(emoji: "🎶", name: "Musique", cost: 4),
        GiftItem(emoji: "🎵", name: "Note de musique", cost: 3),
        GiftItem(emoji: "💫", name: "Tourbillon", cost: 6),
        GiftItem(emoji: "⚡", name: "Éclair", cost: 7),
        GiftItem(emoji: "🔥", name: "Flamme", cost: 8),
        GiftItem(emoji: "💨", name: "Vent", cost: 2),
        GiftItem(emoji: "🌊", name: "Vague", cost: 5),
        GiftItem(emoji: "🌟", name: "Étoile brillante", cost: 6),
        GiftItem(emoji: "🎈", name: "Ballon", cost: 3),
        GiftItem(emoji: "🎂", name: "Gâteau", cost: 10),
        GiftItem(emoji: "🍿", name: "Popcorn", cost: 4),
        GiftItem(emoji: "🎁", name: "Cadeau surprise", cost: 9),
        GiftItem(emoji: "🎇", name: "Feu d’artifice", cost: 12),
        GiftItem(emoji: "🎆", name: "Explosion lumineuse", cost: 12),
        GiftItem(emoji: "🪄", name: "Baguette magique", cost: 15),
        GiftItem(emoji: "🛎️", name: "Cloche", cost: 2),
        GiftItem(emoji: "📯", name: "Trompette", cost: 4),
        GiftItem(emoji: "🎺", name: "Trumpet", cost: 6),
        GiftItem(emoji: "🥁", name: "Tambour", cost: 5),
        GiftItem(emoji: "🪘", name: "Djembe", cost: 7),
        GiftItem(emoji: "🪇", name: "Clochettes", cost: 3),
        GiftItem(emoji: "🕹️", name: "Joystick", cost: 8),
        GiftItem(emoji: "🎤", name: "Microphone", cost: 5),
        GiftItem(emoji: "🎧", name: "Casque", cost: 4),
        GiftItem(emoji: "🎬", name: "Clap cinéma", cost: 6),
        GiftItem(emoji: "📸", name: "Appareil photo", cost: 7),
        GiftItem(emoji: "📹", name: "Caméra", cost: 8),
        GiftItem(emoji: "🎮", name: "Manette", cost: 6),
        GiftItem(emoji: "🪁", name: "Cerf-volant", cost: 3),
        GiftItem(emoji: "🎯", name: "Cible", cost: 4),
        GiftItem(emoji: "🏹", name: "Arc et flèche", cost: 7),
        GiftItem(emoji: "🥌", name: "Curling", cost: 6),
        GiftItem(emoji: "🏓", name: "Ping-pong", cost: 5),
        GiftItem(emoji: "🏸", name: "Badminton", cost: 5),
        GiftItem(emoji: "🎳", name: "Bowling", cost: 7),
        GiftItem(emoji: "🛹", name: "Skateboard", cost: 8),
        GiftItem(emoji: "🛷", name: "Luge", cost: 6),
        GiftItem(emoji: "🚴", name: "Vélo", cost: 7),
        GiftItem(emoji: "🏊", name: "Natation", cost: 5),
        GiftItem(emoji: "🏄", name: "Surf", cost: 6),
        GiftItem(emoji: "⛷️", name: "Ski", cost: 7),
        GiftItem(emoji: "🏂", name: "Snowboard", cost: 8),
        GiftItem(emoji: "🤹", name: "Jonglage", cost: 5),
        GiftItem(emoji: "🎪", name: "Cirque", cost: 10),
        GiftItem(emoji: "🎭", name: "Masque théâtre", cost: 9),
      ],
    ),
    GiftCategory(
      id: 'exclusive',
      label: 'Exclusifs',
      emoji: '👑',
      gifts: [
        GiftItem(emoji: "🚀", name: "Rocket", cost: 50, isPremium: true),
        GiftItem(emoji: "🏆", name: "Trophée", cost: 75, isPremium: true),
        GiftItem(emoji: "💎", name: "Diamant géant", cost: 80, isPremium: true),
        GiftItem(emoji: "👑", name: "Couronne royale", cost: 90, isPremium: true),
        GiftItem(emoji: "💰", name: "Sac d'argent", cost: 70, isPremium: true),
        GiftItem(emoji: "🪙", name: "Pile de pièces", cost: 60, isPremium: true),
        GiftItem(emoji: "🏅", name: "Médaille d’or", cost: 65, isPremium: true),
        GiftItem(emoji: "🥇", name: "Première place", cost: 85, isPremium: true),
        GiftItem(emoji: "🥈", name: "Deuxième place", cost: 75, isPremium: true),
        GiftItem(emoji: "🥉", name: "Troisième place", cost: 70, isPremium: true),
        GiftItem(emoji: "🪐", name: "Planète", cost: 80, isPremium: true),
        GiftItem(emoji: "🌌", name: "Galaxie", cost: 95, isPremium: true),
        GiftItem(emoji: "🌠", name: "Étoile filante", cost: 90, isPremium: true),
        GiftItem(emoji: "🛸", name: "OVNI", cost: 85, isPremium: true),
        GiftItem(emoji: "⚜️", name: "Fleur de lys", cost: 60, isPremium: true),
        GiftItem(emoji: "🏰", name: "Château", cost: 70, isPremium: true),
        GiftItem(emoji: "🗡️", name: "Épée légendaire", cost: 80, isPremium: true),
        GiftItem(emoji: "🛡️", name: "Bouclier royal", cost: 75, isPremium: true),
        GiftItem(emoji: "🎖️", name: "Décoration militaire", cost: 65, isPremium: true),
        GiftItem(emoji: "🧿", name: "Œil protecteur", cost: 55, isPremium: true),
        GiftItem(emoji: "🕹️", name: "Joystick doré", cost: 60, isPremium: true),
        GiftItem(emoji: "📀", name: "CD en or", cost: 50, isPremium: true),
        GiftItem(emoji: "🎹", name: "Piano luxueux", cost: 90, isPremium: true),
        GiftItem(emoji: "🎷", name: "Saxophone doré", cost: 85, isPremium: true),
        GiftItem(emoji: "🎺", name: "Trumpet prestige", cost: 80, isPremium: true),
        GiftItem(emoji: "🏎️", name: "Voiture de sport", cost: 95, isPremium: true),
        GiftItem(emoji: "🛳️", name: "Yacht", cost: 100, isPremium: true),
        GiftItem(emoji: "✈️", name: "Jet privé", cost: 120, isPremium: true),
        GiftItem(emoji: "🛰️", name: "Satellite", cost: 110, isPremium: true),
        GiftItem(emoji: "🦄", name: "Licorne", cost: 75, isPremium: true),
        GiftItem(emoji: "🐉", name: "Dragon", cost: 85, isPremium: true),
        GiftItem(emoji: "🦁", name: "Lion majestueux", cost: 70, isPremium: true),
        GiftItem(emoji: "🐅", name: "Tigre", cost: 65, isPremium: true),
        GiftItem(emoji: "🦅", name: "Aigle royal", cost: 60, isPremium: true),
        GiftItem(emoji: "🌞", name: "Soleil", cost: 80, isPremium: true),
        GiftItem(emoji: "🌛", name: "Lune", cost: 75, isPremium: true),
        GiftItem(emoji: "🌈", name: "Arc-en-ciel", cost: 70, isPremium: true),
        GiftItem(emoji: "⚡", name: "Éclair magique", cost: 85, isPremium: true),
        GiftItem(emoji: "💫", name: "Poussière d’étoiles", cost: 80, isPremium: true),
        GiftItem(emoji: "🪄", name: "Baguette magique", cost: 90, isPremium: true),
        GiftItem(emoji: "🏹", name: "Arc royal", cost: 70, isPremium: true),
        GiftItem(emoji: "🛡️", name: "Bouclier doré", cost: 75, isPremium: true),
        GiftItem(emoji: "🎯", name: "Cible ultime", cost: 60, isPremium: true),
        GiftItem(emoji: "🎟️", name: "Ticket VIP", cost: 65, isPremium: true),
        GiftItem(emoji: "🛎️", name: "Cloche prestigieuse", cost: 50, isPremium: true),
        GiftItem(emoji: "📸", name: "Appareil photo luxe", cost: 70, isPremium: true),
        GiftItem(emoji: "🖼️", name: "Tableau précieux", cost: 85, isPremium: true),
        GiftItem(emoji: "💎", name: "Joyau rare", cost: 95, isPremium: true),
        GiftItem(emoji: "🏆", name: "Trophée légendaire", cost: 100, isPremium: true),
      ],
    ),
  ];
